server.document-root = "/mnt/sdcard/captive_portal/www/"
dir-listing.activate = "disable"
server.errorlog = "/mnt/sdcard/captive_portal/logs/lighttpd.log"
#server.port = 443
$SERVER["socket"] == ":443" {
  ssl.engine = "enable" 
  ssl.pemfile = "/data/data/com.android.myapplication/files/lighttpd.pem" 
}
server.error-handler-404 = "/index.html"
server.tag = "grey-box.ca"
index-file.names = ( "index.php", "index.html", "index.htm" )
fastcgi.map-extensions = ( ".php3" => ".php", ".php4" => ".php", ".php5" => ".php" )
fastcgi.server = (
    ".php" => ((
        "host" => "127.0.0.1",
        "port" => 9998,
        "bin-path" => "/data/data/com.android.myapplication/files/php",
        "bin-environment" => (
            "PHP_FCGI_CHILDREN" => "0",
            "PHP_FCGI_MAX_REQUESTS" => "10000",
            "TMPDIR" => "/data/data/com.android.myapplication/tmp/"
        ),
        "min-procs" => 0,
        "max-procs" => 1,
        "idle-timeout" => 20
    ))
)

server.pid-file = "/data/data/com.android.myapplication/files/lighttpd.pid"
server.max-request-size = 1000000

server.modules = (
  "mod_openssl",
  "mod_fastcgi"
)
